export type Language = { label: string; value: string }

export const LANGUAGES: Language[] = [
  { label: "Plain Text", value: "plaintext" },
  { label: "TypeScript", value: "typescript" },
  { label: "JavaScript", value: "javascript" },
  { label: "TSX", value: "typescriptreact" },
  { label: "JSX", value: "javascriptreact" },
  { label: "Python", value: "python" },
  { label: "Rust", value: "rust" },
  { label: "Go", value: "go" },
  { label: "Java", value: "java" },
  { label: "C#", value: "csharp" },
  { label: "C++", value: "cpp" },
  { label: "C", value: "c" },
  { label: "PHP", value: "php" },
  { label: "Ruby", value: "ruby" },
  { label: "Swift", value: "swift" },
  { label: "Kotlin", value: "kotlin" },
  { label: "Dart", value: "dart" },
  { label: "Shell / Bash", value: "shell" },
  { label: "PowerShell", value: "powershell" },
  { label: "SQL", value: "sql" },
  { label: "HTML", value: "html" },
  { label: "CSS", value: "css" },
  { label: "SCSS", value: "scss" },
  { label: "JSON", value: "json" },
  { label: "YAML", value: "yaml" },
  { label: "XML", value: "xml" },
  { label: "Markdown", value: "markdown" },
  { label: "Dockerfile", value: "dockerfile" },
  { label: "GraphQL", value: "graphql" },
  { label: "Prisma", value: "prisma" },
  { label: "TOML", value: "toml" },
  { label: "Lua", value: "lua" },
  { label: "R", value: "r" },
]
